# Generated by Django 4.2.1 on 2023-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='hour',
            field=models.IntegerField(default=1),
        ),
    ]
