# Generated by Django 4.2.1 on 2023-06-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='hour1',
            field=models.IntegerField(default=1),
        ),
    ]
